set_input_delay -clock cpu_bsc_75M -min 0.200 [get_ports CPU_WE0_N]
set_input_delay -clock cpu_bsc_75M -max 0.500 [get_ports CPU_WE0_N]
set_input_delay -clock cpu_bsc_75M -min 0.200 [get_ports CPU_CS1_N]
set_input_delay -clock cpu_bsc_75M -max 0.500 [get_ports CPU_CS1_N]
set_input_delay -clock cpu_bsc_75M -min 0.200 [get_ports CPU_DATA*]
set_input_delay -clock cpu_bsc_75M -max 0.500 [get_ports CPU_DATA*]
set_input_delay -clock cpu_bsc_75M -min 0.200 [get_ports CPU_ADDR*]
set_input_delay -clock cpu_bsc_75M -max 0.500 [get_ports CPU_ADDR*]
set_output_delay -clock cpu_bsc_75M -min 0.200 [get_ports CPU_DATA*]
set_output_delay -clock cpu_bsc_75M -max 0.500 [get_ports CPU_DATA*]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
