[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.clean]
script_runner = "@shell"
script = '''
rm *.jou
rm *.log
rm *.zip
rm *.prm
rm *.str
rm *.pb
rm *.mcs
rm *.xpr
rm -rf .Xil
rm -rf autd3-fpga.ip_user_files
rm -rf autd3-fpga.cache
rm -rf autd3-fpga.gen
rm -rf autd3-fpga.hw
rm -rf autd3-fpga.runs
rm -rf autd3-fpga.sim
rm -rf autd3-fpga.srcs
'''

[tasks.build]
script_runner = "python"
script_extension = "py"
script = { file = "find_vivado.py" }
